version: '2'
services:
  apache:
    image: rafaelcgstz/magento2
    # build: .
    ports:
      - "80:80" # web
      #- "9001:9000" # xdebug
      # - "35729:35729" # live reload
    volumes:
      - ./src:/var/www/html/
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
      # - elasticsearch
      - redis
      - redis-session
    networks:
      - mkdnetwork

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mkd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
      - ./data:/var/lib

    networks:
      - mkdnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - mkdnetwork

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - mkdnetwork

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - mkdnetwork

  # elasticsearch:
  #   #image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
  #   build: './elasticsearch'
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - ./elasticsearchdata:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - mkdnetwork

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mkdnetwork

networks:
  mkdnetwork:
    driver: bridge

volumes:
  dbdata:
    driver: local
